version: '3.4'

services: 
  api:
    container_name: datastreamer_api
    build: ./DataStreamer.API
    ports:
      - 32331:80
    networks:
      - DataStreamer
    environment:
      - javapath=/usr/bin/java
      - generatorpath=/app/Libraries/generator.jar
      - profilepath=/app/Libraries/profile.json
      
  frontend:
    container_name: datastreamer_frontend
    build: ./DataStreamer.Frontend
    ports:
      - 32330:3000
    environment:
      - NODE_ENV=development
    networks:
      - DataStreamer

networks:
  DataStreamer:
